config/routes.rb
Honolua::Application.routes.draw do
  
  get 'admin' => 'admin#index'

  controller :sessions do 
    get     'login' => :new
    post    'login' => :create
    delete  'logout' => :destroy
  end

  get '/signup' => 'users#new'
  
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products

  get "store/index"

  root 'store#index', as: 'store'

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	# If a cart is destroyed (its record in db is deleted, Rails deletes any line items that are associated with that cart
	has_many :line_items, dependent: :destroy

	# Checks if list items includes current product we're adding. 
	# If it does increments the quantity If it doesn't it builds a new LineItem.
	def add_product(product_id)
		current_item = line_items.find_by(product_id: product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
			current_item
	end

	# Sum the prices of each item in the collection
	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :require_buyer
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # Whitelisting: mark following method as NOT required.
  # But only skip authorize() for create, update & destroy (So users can manage their own carts).
  skip_before_action :authorize, only: [:create, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    # Ensure user can only delete their own cart
    # @cart.destroy if @cart.id == session[:cart_id]
    
    @cart.destroy

    # Remove the cart from the session
    # session[:cart_id] = nil

    respond_to do |format|
      # Redirect to index with a notification
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      # Use the rails logger to record the error (log/development.log)
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="panel panel-success">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <b>Your Cart</b>
  </div>
  <!-- Table -->
  <table class="table">
    <tr>
      <th>Product Name</th>
      <th>Quantity</th>
    </tr>

    <!-- 
      The render() method will iterate over any collection that is passed to it.
      A partial can invoke other partials.
     -->
    <% unless cart.line_items.empty? %>
      <%= render(cart.line_items) %>
    <% end %>
    
    <tr>
      <th>Total</th>
      <td><%= number_to_currency(cart.total_price) %></td>
    </tr>
  </table>
</div>

<div class="btn-group btn-group-sm" role="group" aria-label="...">
  <%= link_to 'Checkout', new_order_path, method: :get, class: 'btn btn-success' %>
  <%= link_to 'Empty cart', cart, method: :delete, data: { confirm: 'Delet Cart ?' }, class: 'btn btn-danger' %>
</div>

app/views/carts/_cart.html.haml
.panel.panel-info
  .panel-heading
    %b Your Cart

  %table{:class => "table"}
    %tr
      %th Product Name
      %th Quantity
      %th Price
    - unless cart.line_items.empty?
      = render(@cart.line_items)
    %tr
      %th Total
      %th
      %th= number_to_currency(cart.total_price)

.btn-group.btn-group-sm
  = link_to 'Checkout', new_order_path, method: :get, class: 'btn btn-success'
  = link_to 'Empty', cart, method: :delete, class: 'btn btn-danger', data: { confirm: 'Delet Cart ?' }

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<!--
 Here we have access to the instance variable @cart set by the controller.
 This var is also available inside partials called from the layout but using
 'cart' instead of '@cart'
-->

<%= render @cart %>