config/routes.rb
Honolua::Application.routes.draw do
  
  get 'admin' => 'admin#index'

  controller :sessions do 
    get     'login' => :new
    post    'login' => :create
    delete  'logout' => :destroy
  end

  get '/signup' => 'users#new'
  
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products

  get "store/index"

  root 'store#index', as: 'store'

  

end

app/views/layouts/_footer.html.haml
%link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}/
%footer
  .footer-bottom
    .container
      %p.pull-left Coded and built with love by Inge. Source code available on GitHub.
      .pull-right

app/views/layouts/_header.html.haml
%nav.nav-header.navbar.navbar-inverse.navbar-static-top
  .container-fluid
    .navbar-header
      %a.navbar-brand{:href => '/'} Honolua SurfShop
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li
            %a
              Signed in as
              = current_user.first_name
              [
              = current_user.role
              mode ]
          / %li= link_to 'Users', users_path
          / %li= link_to 'Orders', orders_path
          / %li= link_to 'Create a Product', new_product_path
          %li= link_to 'Log out', logout_path, method: 'delete'
        - else
          %li= link_to 'Login', login_path
          %li= link_to 'Signup', signup_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Honolua SurfShop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body class='<%= controller.controller_name %>'>

	<%= render "layouts/header" %>

	<div id="main" class="clearfix">
		<div id="left-bar">
		<!-- Only show cart if cart exists and the user is logged in and is a buyer -->
		<% if current_user %>
			<% if @cart && current_user.buyer? %>
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
					<%= render @cart %>
				<% end %>
			<% elsif current_user.seller? %>
				<button id="admin-panel-btn" type="button" class="btn btn-success">
					<%= link_to 'New Product', new_product_url %>
				</button>
			<% elsif current_user.admin? %>
				<button id="admin-panel-btn" type="button" class="btn btn-danger">
					<%= link_to 'Admin Panel', admin_url %>
				</button>
			<% end %>
		<% end %>
		</div>
		<div id="content">
			<%= yield %>
		</div>
	</div>

	<%= render "layouts/footer" %>

</body>
</html>